apiVersion: v1
kind: Service
metadata:
  name: mutating-webhook-demo
  namespace: mutating-webhook-demo
spec:
  ports:
    - port: 9443
      targetPort: 9443
      name: https
  selector:
    app: mutating-webhook-demo
